### ISSUE TITLE
Export wrapped keys from TSS.Net and import in TSS.CPP fails

### ISSUE THREAD

**Issue by ghost** [microsoft/TSS.MSR#27]
Hi, 

I am trying to serialize a signing key I create in a C#-application with TSS.Net and deserialize it in a C++ application (using TSS.CPP) to use it.
I am serializing the key with 

            byte[] serializedPublic = publicKey.GetTpmRepresentation();

Deserializing this in C# works fine using:

          Marshaller.FromTpmRepresentation<TpmPublic>(serializedPublic);

Now I save the byte[] to disk. In the C++-application I read that byte[] and try to deserialize it with

           TPMT_PUBLIC publicKey;
           publicKey.FromBuf(wrappedPublic, TpmTypeId::TPMT_PUBLIC_ID);

The documentation is a little bit confusing at this point, so perhaps I am using the wrong methods.
However this fails, because in MarshallIn in line 111 I always get TpmTypeID::None when parsing the TPM_PUBLIC_PARMS of the key. So later in line 118

        newObj = TpmStructureBase::Factory(typeOfUnion, fInfo.ThisElementType, pUnion2);

an runtime_error("Factory only makes TPM structs and unions");) is thrown.
I am sure I am missing something or just calling the wrong methods. 
Can you please help me to track down this issue?

**Comment by amarochk** [comment]
Hi Frank,

What are the parameters of the key you serialize in your C# code?

-Andrey

**Comment by Frank667** [comment]
Hi Andrey,

the template is:

`TpmPublic keyInPublic = new TpmPublic(
                TpmAlgId.Sha1,                                 
                ObjectAttr.Sign |                              
                ObjectAttr.FixedParent | ObjectAttr.FixedTPM |  
                ObjectAttr.UserWithAuth | ObjectAttr.SensitiveDataOrigin,
                new byte[0],                                  
                new RsaParms(                                  
                    new SymDefObject(),                        
                    new NullAsymScheme(),
                    2048, 0),
                new Tpm2bPublicKeyRsa());`

and the key creation code
`TpmPrivate privateKey = tpm[keyAuth].Create(primHandle,
                                               sensCreate,
                                               keyInPublic,
                                               outsideInfo,
                                               new PcrSelection[0],
                                               out publicKey,
                                               out keyCreationData,
                                               out creationHash,
                                               out creationTicket);`

But I found out that the problem seems to be with the STL container std::vector<BYTE> passed to FromBuf(). I wrote a little test and  fired up the debugger and there I see that the contents of the vector change when passing the boundary to the TSS.CPP.dll. After changing the parameters to `PBYTE buf and int length` everything worked again. The same happens if  I leave the method signature untouched but make the project part of my solution and compile it together.
Perhaps the usage could be documented a little bit better? Alternatively the siganture of the exposed methods should not take STL containers.

Regards,
Frank
