### ISSUE TITLE
Get error when try to create primary TMP

### ISSUE THREAD

**Issue by Peymanmi** [microsoft/TSS.MSR#46]
Hi @amarochk ,

When I run any sample (as administrator) in Windows 10, I get the following error in `tpm.CreatePrimary`

`GetTpmAuth(LOCKOUT): error 0x80284015  (OWNERAUTH_NOT_FOUND)`

Thanks for your help in advance.

**Comment by RonaldAi** [comment]
Hi Peymanmi,
this error is likely due to a missing owner authorization in the registry. The sample code tries to load that authorization value and fails. There are multiple reason why your machine could be in that state. Can you have a look at https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/change-the-tpm-owner-password and https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/initialize-and-configure-ownership-of-the-tpm to see if that fixes your issue?
Thanks, Ron.

**Comment by Peymanmi** [comment]
Hi Ron,

Thanks for your help,  now could run the sample without any error.

Just I'm wondering to know is there any way to use this lib to generate the TPM Virtual Smart Card?

Thanks,
Peyman

**Comment by RonaldAi** [comment]
Hi Peyman,
sorry, I don't think there are any samples to show usage of this library to generate TPM Virtual Smart Cards.
I assume you are familiar with: https://docs.microsoft.com/en-us/windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-overview which gives a good overview about TPM VSC supported in Windows. 
Cheers, Ron.
