### ISSUE TITLE
Tbsi_Get_OwnerAuth can't get real OwnerAuth

### ISSUE THREAD

**Issue by AlanZsm** [microsoft/TSS.MSR#64]
I'm trying to output the OwnerAuth in NV (Windows) sample as below:
                byte[] ownerAuth;
                if (GetOwnerAuthFromOS(out ownerAuth))
                {
                    tpm.OwnerAuth = ownerAuth;
                    Console.WriteLine("OwnerAuth: {0}", BitConverter.ToString(ownerAuth));
                }
I tried it on 2 of my computer, but it always return all zero value, while the actuall OwnerAuth is not null (read by get-tpm with power shell):
Running as Administrator. Deleting and re-creating NV entry.
OwnerAuth: 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00

It is a bug?

**Comment by amarochk** [comment]
Tbsi_Get_OwnerAuth() is a Win32 API outside of the TSS.Net control. TSS.Net can only accept what it receives from it. Otherwise it is the user's responsibility to supply correct auth values. Windows have been changing the way it manages the TPM auth values, and Windows 10 normally leaves TPM_RH_OWNER auth value an empty value. If your code gets BadAuth response when using TpmRh.Owner handle you could try to use the value returned by Get-Tpm (though it may not be the actual auth value if your Windows was configured by someone to use it).

**Comment by AlanZsm** [comment]
Thanks for explanation!
