### ISSUE TITLE
NVWrite prohibit

### ISSUE THREAD

**Issue by MarcBorgers** [microsoft/TSS.MSR#66]
Is there a way to prohibit that a NVWrite can be done on an index with a different Auth than before?

**Comment by amarochk** [comment]
Your question is unclear. Anyone who knows the current auth value can write an index with TPMA_NV_AUTHWRITE attribute. Any previous auth values do not exist for the TPM (i.e. it does not maintain any history of auth values).

**Comment by MarcBorgers** [comment]
Yes, my remark is the following one can always use NvUndefineSpace and then the data is lost on that index. is there a way to prevent that?

**Comment by MarcBorgers** [comment]
NvUndefineSpace does not have an Auth

**Comment by amarochk** [comment]
Anyone who knows TPM_RH_OWNER auth value (normally empty in Windows 10) can delete the index. It is designed this way to avoid NV memory loss because of buggy/malicious apps. The only other way is to use POLICY_DELETE attribute, but this requires access to TPM_RH_PLATFORM that is only available to the firmware during early boot.
